# Generated by Django 5.1.1 on 2024-10-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_remove_user_username_user_birthdate_user_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
