# Generated by Django 5.1.1 on 2024-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, max_length=1200, null=True, upload_to='profile_pics/'),
        ),
    ]
