# Generated by Django 5.1.1 on 2024-10-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0006_remove_user_birthdate_user_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('seller', 'Seller'), ('contributor', 'Contributor')], default='', max_length=12, verbose_name='Account Type'),
        ),
    ]
