# Generated by Django 5.1.1 on 2024-10-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0008_alter_user_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'administator'), ('seller', 'Seller'), ('contributor', 'Contributor')], default='', max_length=12, verbose_name='Account Type'),
        ),
    ]
