# Generated by Django 5.1.1 on 2024-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_created=True)),
                ('product_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('product_quantity', models.IntegerField(verbose_name='Product Quantity')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_image', models.ImageField(max_length=1200, upload_to='products/')),
            ],
        ),
    ]
