# Generated by Django 5.1.1 on 2024-10-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='المنتجات المرتجعة؟'),
        ),
    ]
