# Generated by Django 5.1.1 on 2024-10-21 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_report_is_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('refund', 'Refund'), ('reinvest', 'Reinvest')], max_length=10, verbose_name='Type')),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.earning', verbose_name='Earning')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.product', verbose_name='Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='مستخدم')),
            ],
        ),
    ]
