# Generated by Django 5.1.1 on 2024-10-21 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='earning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.earning', verbose_name='كسب'),
        ),
        migrations.AlterField(
            model_name='request',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='dashboard.product', verbose_name='مشروع'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('refund', 'استرداد'), ('reinvest', 'إعادة الاستثمار')], max_length=10, verbose_name='يكتب'),
        ),
    ]
