# Generated by Django 5.1.1 on 2024-11-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_notificationscounter_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('refund', 'استرداد'), ('reinvest', 'إعادة الاستثمار')], max_length=10, verbose_name='نوع الطلب'),
        ),
    ]
