# Generated by Django 5.1.1 on 2024-11-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_request_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='عنوان البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم التليفون')),
                ('role', models.CharField(choices=[('contributer', 'مساهم'), ('seller', 'بائع')], max_length=20, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
