# Generated by Django 5.1.1 on 2024-11-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_joinrequests_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default='product_001', max_length=120, unique=True, verbose_name='Product Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinrequests',
            name='role',
            field=models.CharField(choices=[('contributer', 'مساهم'), ('seller', 'بائع')], max_length=20, verbose_name='دور'),
        ),
    ]
