# Generated by Django 5.1.1 on 2024-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_product_product_image_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Request Status'),
        ),
    ]
